=== CampusPulse/bus-data-schema/Schema/apartmentComplex.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://rithousing.com/apartmentComplex.schema.json",
    "title": "Apartment Complex data for RIT Housing Comparison Website",
    "description": "All the data for every apartment complex and unit type used in this website.",
    "type": "object",
    "properties": {
        "apartmentName": {
            "description": "The name of the apartment complex",
            "type": "string"
        },
        "address": {
            "description": "Address of the apartment complex",
            "type": "string",
            "pattern": "^(\\d{1,}) [a-zA-Z0-9\\s]+(\\,)? [a-zA-Z]+(\\,)? [A-Z]{2} [0-9]{5,6}$"
        },
        "onCampus": {
            "description": "Is the apartment on campus?",
            "type": "boolean"
        },
        "avgRentCost": {
            "description": "Average cost of rent between each unit type",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "timestamp": {
                        "description": "Timestamp of recorded change in price: yyyy-mm-dd hh:mm:ss",
                        "type": "string",
                        "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$"
                    },
                    "minCost": {
                        "description": "Minimum average cost of rent",
                        "type": "number",
                        "exclusiveMinimum": 0
                    },
                    "maxCost": {
                        "description": "Maximum average cost of rent",
                        "type": "number",
                        "exclusiveMinimum": 0
                    }
                },
                "required": ["timestamp","minCost","maxCost"]
            }
        },
        "avgUtilitiesCost": {
            "description": "Average cost of utilities between each unit type",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "timestamp": {
                        "description": "Timestamp of recorded change in price: yyyy-mm-dd hh:mm:ss",
                        "type": "string",
                        "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$"
                    },
                    "cost": {
                        "description": "Average cost of utilities",
                        "type": "number"
                    }
                },
                "required": ["timestamp","cost"]
            }
        },
        "renewable": {
            "description": "Describing if the apartment is renewable",
            "type": "boolean"
        },
        "subletPolicy": {
            "description": "Describe the sublet policy of the apartment",
            "type": "string"
        },
        "reletPolicy": {
            "description": "Describe the relet policy of the apartment",
            "type": "string"
        },
        "imageFile": {
            "description": "Path to image file on disk",
            "type": "string"
        },
        "imageUrl": {
            "description": "Url link to image file from apartment website",
            "type": "string"
        },
        "description": {
            "description": "Description of the apartment complex. Index 0 is short, Index 1 is long",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 2,
            "maxItems": 2,
            "uniqueItems": true
        },
        "topAmenities": {
            "description": "The 4 top amenities at this apartment",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "amenityName": {
                        "description": "name of the amenity",
                        "type": "string"
                    },
                    "amenityDescription": {
                        "description": "Description of the amenity",
                        "type": "string"
                    },
                    "amenityIcon": {
                        "description": "  icon for the amenity",
                        "type": "string"
                    }
                },
                "required": ["amenityName","amenityDescription", "amenityIcon"]
            },
            "minItems": 4,
            "maxItems": 4
        },
        "phoneNumber": {
            "description": "Phone number of the apartment",
            "type": "string",
            "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
        },
        "email": {
            "description": "Email address for the apartment",
            "type": "string",
            "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        },
        "website": {
            "description": "Website for the apartment",
            "type": "string"
        },
        "apartmentAmenities": {
            "description": "All amentities for the apartment (not units)",
            "type": "object",
            "properties": {
                "accessibility": {
                    "description": "Accessibility accomodations",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "accomodationName": {
                                "description": "name of the accessibility accomodation",
                                "type": "string"
                            },
                            "accomodationDescription": {
                                "description": "Description of the accomodation",
                                "type": "string"
                            },
                            "accomodationIcon": {
                                "description": "  icon for the accessibility accomodation",
                                "type": "string"
                            }
                        },
                        "required": ["accomodationName","accomodationDescription", "accomodationIcon"]
                    }
                },
                "amenities": {
                    "description": "All amenities for the apartment (not units)",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "amenityName": {
                                "description": "name of the amenity",
                                "type": "string"
                            },
                            "amenityDescription": {
                                "description": "Description of the amenity",
                                "type": "string"
                            },
                            "amenityIcon": {
                                "description": "  icon for the amenity",
                                "type": "string"
                            }
                        },
                        "required": ["amenityName","amenityDescription", "amenityIcon"]
                    }
                }
            },
            "required": ["amenities"]
        },
        "transit": {
            "description": "Transit times using common transportation to popular locations on campus",
            "type": "object",
            "properties": {
                "ritShuttle": {
                    "description": "RIT Shuttle times",
                    "type": "object",
                    "properties": {
                        "description": {
                            "description": "Any notes about this transit option",
                            "type": "string"
                        },
                        "fLot": {
                            "description": "Time to F Lot in minutes",
                            "type": "integer"
                        },
                        "sLot": {
                            "description": "Time to S Lot in minutes",
                            "type": "integer"
                        },
                        "NTID": {
                            "description": "Time to NTID in minutes",
                            "type": "integer"
                        },
                        "gordonFieldHouse": {
                            "description": "Time to Gordon Field House in minutes",
                            "type": "integer"
                        }
                    },
                    "required": ["description","fLot"]
                },
                "privateShuttle": {
                    "description": "Private Shuttle times",
                    "type": "object",
                    "properties": {
                        "description": {
                            "description": "Any notes about this transit option",
                            "type": "string"
                        },
                        "fLot": {
                            "description": "Time to F Lot in minutes",
                            "type": "integer"
                        },
                        "sLot": {
                            "description": "Time to S Lot in minutes",
                            "type": "integer"
                        },
                        "ntid": {
                            "description": "Time to ntid in minutes",
                            "type": "integer"
                        },
                        "gordonFieldHouse": {
                            "description": "Time to Gordon Field House in minutes",
                            "type": "integer"
                        }
                    },
                    "required": ["description","fLot","sLot","ntid","gordonFieldHouse"]
                },
                "car": {
                    "description": "Personal car times",
                    "type": "object",
                    "properties": {
                        "description": {
                            "description": "Any notes about this transit option",
                            "type": "string"
                        },
                        "fLot": {
                            "description": "Time to F Lot in minutes",
                            "type": "integer"
                        },
                        "sLot": {
                            "description": "Time to S Lot in minutes",
                            "type": "integer"
                        },
                        "ntid": {
                            "description": "Time to ntid in minutes",
                            "type": "integer"
                        },
                        "gordonFieldHouse": {
                            "description": "Time to Gordon Field House in minutes",
                            "type": "integer"
                        }
                    },
                    "required": ["description","fLot","sLot","ntid","gordonFieldHouse"]
                },
                "biking": {
                    "description": "Biking times",
                    "type": "object",
                    "properties": {
                        "description": {
                            "description": "Any notes about this transit option",
                            "type": "string"
                        },
                        "fLot": {
                            "description": "Time to F Lot in minutes",
                            "type": "integer"
                        },
                        "sLot": {
                            "description": "Time to S Lot in minutes",
                            "type": "integer"
                        },
                        "ntid": {
                            "description": "Time to ntid in minutes",
                            "type": "integer"
                        },
                        "gordonFieldHouse": {
                            "description": "Time to Gordon Field House in minutes",
                            "type": "integer"
                        }
                    },
                    "required": ["description","fLot","sLot","ntid","gordonFieldHouse"]
                },
                "walking": {
                    "description": "Walking times",
                    "type": "object",
                    "properties": {
                        "description": {
                            "description": "Any notes about this transit option",
                            "type": "string"
                        },
                        "fLot": {
                            "description": "Time to F Lot in minutes",
                            "type": "integer"
                        },
                        "sLot": {
                            "description": "Time to S Lot in minutes",
                            "type": "integer"
                        },
                        "ntid": {
                            "description": "Time to ntid in minutes",
                            "type": "integer"
                        },
                        "gordonFieldHouse": {
                            "description": "Time to Gordon Field House in minutes",
                            "type": "integer"
                        }
                    },
                    "required": ["description","fLot","sLot","ntid","gordonFieldHouse"]
                }
            },
            "required": []
        },
        "unitTypes": {
            "description": "Unit types in this apartment complex",
            "type": "array",
            "items": {
                "$ref": "./unitType.schema.json"
            }
        }
    },
    "required": ["apartmentName","address","onCampus","avgRentCost","avgUtilitiesCost","renewable","imageFile","imageUrl",
        "description","topAmenities","phoneNumber","email","website","apartmentAmenities","transit"]
}

=== CampusPulse/bus-data-schema/Schema/apex.json
{
    "$schema": "./apartmentComplex.schema.json",

    "apartmentName": "Apex Apartments",
    "address": "380 John Street, Rochester, NY 14623",
    "onCampus": false,
    "description": ["The largest student housing complex in upstate NY, Apex has lots of amenities to satisfy anyone, including a pool & hot tub, eSports Arena, VR Room, and outdoor patio area.","The largest student housing complex in upstate NY, Apex has lots of amenities to satisfy anyone, including a pool & hot tub, eSports Arena, VR Room, and outdoor patio area. Apex is comprised of two large buildings that each house hundreds of people, so fire alarms are common. Unfortunately, its very easy to set off a building-wide fire alarm, forcing everyone in the building to evacuate. The mailroom leaves much to be desired, as packages can take up to a week to be processed and available for pickup after delivery. The construction is cheap, and the bedrooms are small. One of the best things about Apex is the kitchens: they are large and feature good appliances."],
    "email": "info@lifeatapex.com",
    "phoneNumber": "(585)565-4600",
    "website": "https://www.lifeatapex.com/",
    "reletPolicy": "You are allowed to relet, but you must find a person to take over your lease.",
    "subletPolicy": "You cannot sublet at Apex.",
    "renewable": true,
    "imageFile": "$lib/assets/apex.jpg",
    "imageUrl": "https://www.passero.com/images/8auJXt.bc53/1300x520/APEX%20Exterior%203.jpg",
    "avgRentCost": [
        {
            "maxCost": 965,
            "minCost": 965,
            "timestamp": "2023-06-19 20:40:34"
        }
    ],
    "avgUtilitiesCost": [
        {
            "cost": 1,
            "timestamp": "2023-06-19 20:44:45"
        }
    ],
    "transit": {
        "ritShuttle": {
            "description": "Normal Apex-to-campus shuttle only stops at NTID and F lot. You can take the full campus loop shuttle that stops everywhere to get to S lot, but that could take anywhere from 20 minutes to an hour depending on the order of stops.",
            "fLot": 5,
            "sLot": 30,
            "ntid": 3
        },
        "car": {
            "description": "You cannot get a campus parking pass without a special exemption.",
            "fLot": 5,
            "sLot": 5,
            "ntid": 3,
            "gordonFieldHouse": 4
        },
        "biking": {
            "description": "",
            "fLot": 8,
            "sLot": 8,
            "ntid": 4,
            "gordonFieldHouse": 6
        },
        "walking": {
            "description": "",
            "fLot": 25,
            "sLot": 20,
            "ntid": 10,
            "gordonFieldHouse": 15
        }
    },
    "topAmenities": [
        {
            "amenityName": "In-unit Kitchen",
            "amenityDescription": "Each unit comes with a fully-featured kitchen",
            "amenityIcon": "kitchen-set"
        },
        {
            "amenityName": "In-unit Laundry room",
            "amenityDescription": "Each unit has its own laundry room",
            "amenityIcon": "jug-detergent"
        },
        {
            "amenityName": "Accessible property",
            "amenityDescription": "Each entrance is handicapped accessible, and there are ADA compliant rooms on the first floor. You can request fire alarm strobes for your room.",
            "amenityIcon": "accessible-icon"
        },
        {
            "amenityName": "eSports Arena",
            "amenityDescription": "Apex has a fully decked-out esports arena, with gaming PCs and next-gen consoles.",
            "amenityIcon": "gamepad"
        }
    ],
    "apartmentAmenities": {
        "accessibility": [
            {
                "accomodationName": "Handicapped Parking",
                "accomodationDescription": "Apex has handicapped parking spots near each entrance, with extra wide spaces for vans.",
                "accomodationIcon": "square-parking"
            },
            {
                "accomodationName": "Handicapped Doors",
                "accomodationDescription": "There are handicapped buttons for each entrance.",
                "accomodationIcon": "door-open"
            },
            {
                "accomodationName": "Elevators",
                "accomodationDescription": "Apex has elevators all around the building, with accessible entrances and controls.",
                "accomodationIcon": "elevator"
            },
            {
                "accomodationName": "Wheelchair-accessible Units",
                "accomodationDescription": "There are some wheelchair accessible units on the 1st floor.",
                "accomodationIcon": "wheelchair"
            },
            {
                "accomodationName": "Fire alarm strobes",
                "accomodationDescription": "You can request fire alarm strobes be installed in your unit if necessary.",
                "accomodationIcon": "fire"
            }
        ],
        "amenities": [
            {
                "amenityName": "Gift cards for signing a lease",
                "amenityDescription": "Apex often gives upwards of $800 gift cards for signing a lease with them. You get the money in a \"Community Rewards\" wallet a couple months after the start of your lease, and can apply it to different gift cards, such as Dave N Busters, Olive Garden, and many more vendors. You can also take it as a Visa e-gift card, to be used to purchase online items.",
                "amenityIcon": "gift"
            },
            {
                "amenityName": "eSports Arena",
                "amenityDescription": "The eSports Arena at Apex includes multiple gaming PC stations, and PlayStation 5 & Xbox Series X consoles.",
                "amenityIcon": "gamepad"
            },
            {
                "amenityName": "Outdoor patio",
                "amenityDescription": "The outdoor patio has firepits and grills, with hard plastic seats. There's a dog-walking area too.",
                "amenityIcon": ""
            },
            {
                "amenityName": "VR Studio",
                "amenityDescription": "There's a VR Room on the 4th floor of Building 1.",
                "amenityIcon": ""
            },
            {
                "amenityName": "Electric Car Chargers",
                "amenityDescription": "For a couple hundred extra dollars per lease, you can charge your electric car at the provided Level 2 chargers on-site.",
                "amenityIcon": ""
            },
            {
                "amenityName": "Pool with Hot Tubs",
                "amenityDescription": "There is a large pool with two hot tubs on the property. The hot tubs are open for most of the year, but the pool is only open for a few months during the summer and the beginning of the fall.",
                "amenityIcon": ""
            },
            {
                "amenityName": "Computer Lab with Printer",
                "amenityDescription": "There is a room on the 2nd floor with Macs and a printer. The printer is very finicky, and only the Apex staff can fix it or replace ink and paper.",
                "amenityIcon": ""
            },
            {
                "amenityName": "Pet Friendly",
                "amenityDescription": "Pets are welcome at Apex! They require a $250 non-refundable fee, plus a DNA sample to register your pet.",
                "amenityIcon": ""
            },
            {
                "amenityName": "Pet Washing Station",
                "amenityDescription": "There's a pet washing station available in Building 1! It has a large area to wash, groom, and clean your pet!",
                "amenityIcon": ""
            },
            {
                "amenityName": "24-Hour Gym",
                "amenityDescription": "There's a 24 hour gym with a strengths, XR fitness, and yoga room in the clubhouse area of Building 1.",
                "amenityIcon": ""
            }
        ]
    },
    "unitTypes": [
        {
            "unitType": "5x5",
            "description": [""," "],
            "floorplanFile": "$lib/assets/floorplan/apex_5x5.webp",
            "floorplanUrl": "https://assets.myrazz.com/9c4992d0-60f5-4225-b237-55cd74969ee8/-/preview/400x400/-/format/auto/-/quality/lighter/-/resize/620x/",
            "bathrooms": 5,
            "bedrooms": 5,
            "shared": false,
            "rentCost": [
                {
                    "maxCost": 965,
                    "minCost": 965,
                    "timestamp": "2023-06-19 20:40:34"
                }
            ],
            "utilitiesCost": [
                {
                    "note": "All utility bills are split evenly between roommates. $30 of gas and electric are covered per person in the unit ($150 total). They split it $20 electic, $10 gas. You get charged for any overages, split evenly between roommates. All other utilities are 100% covered.",
                    "electricCost": 20,
                    "gasCost": 10,
                    "internetCost": 0,
                    "sewerCost": 0,
                    "waterCost": 0,
                    "timestamp": "2023-06-19 20:44:45"
                }
            ],
            "topAmenities": [
                {
                    "amenityName": "In-unit Kitchen",
                    "amenityDescription": "Each unit comes with a fully-featured kitchen",
                    "amenityIcon": ""
                },
                {
                    "amenityName": "In-unit Laundry",
                    "amenityDescription": "Each unit has its own laundry room",
                    "amenityIcon": ""
                },
                {
                    "amenityName": "Fully furnished",
